### ISSUE TITLE
go-git v5.11.0 inittask panic

### ISSUE THREAD

**Issue by TheMightyGit** [eh-steve/goloader#28]
Go version: go 1.21.5
MacOS: 12.7 (x86)
goloader: 684a15fbb234

In my outer program I import and use `github.com/go-git/go-git/v5` and `github.com/go-git/go-git/v5/plumbing` (it's a pure go package, no cgo, v5.11.0).  These packages are NOT used in my JIT'd code. However, when I use either `fmt.Println()` or `time.Sleep()` in the JIT code and I get this panic...

```
still have 4 unresolved external symbols despite building and linking dependencies...:
github.com/go-git/gcfg/scanner..inittask     required by:
    github.com/go-git/gcfg..inittask

github.com/go-git/gcfg/token..inittask     required by:
    github.com/go-git/gcfg..inittask

github.com/go-git/gcfg/types.EnumParser.Parse     required by:
    github.com/go-git/gcfg.boolSetter

gopkg.in/warnings%2ev0..inittask     required by:
    github.com/go-git/gcfg..inittask
```

If I remove `go-git` from my outer code everything is fine.

Happy to provide more details if needed.

**Comment by eh-steve** [comment]
Would you mind trying on this branch

https://github.com/eh-steve/goloader/pull/27

**Comment by TheMightyGit** [comment]
@eh-steve Yes! That fixes it :)

**Comment by eh-steve** [comment]
Great, I just need to massage the CI on that PR before I merge it so there might be some rebases before it ends up in master.

**Comment by eh-steve** [comment]
Merged into master, let me know if it works for you and I'll close this issue

**Comment by TheMightyGit** [comment]
> Merged into master, let me know if it works for you and I'll close this issue

@eh-steve It works for me on master now. Thank you! :)
