### ISSUE TITLE
PCREL offset of `go.string` may greater than 32 bits

### ISSUE THREAD

**Issue by fumeboy** [eh-steve/goloader#9]
here allocating `go.string` on the heap may lead to R_PCREL offset greater than 32 bits

https://github.com/eh-steve/goloader/blob/9fbc78a6d5210680c45d9d54dedbaf66c1314e42/ld.go#L313

**Comment by eh-steve** [comment]
Yeah I know, that's why we still have the relocation epilogues

**Comment by eh-steve** [comment]
Closing this as I don't think it's an issue
